export const loaderMessages = [
  "Let's make talking to people feel easier",
  "Good chats start right here",
  "Ready to turn strangers into friends?",
  "Life's better when we talk to each other",
  "You never know who you'll meet today",
  "Simple hellos lead to amazing friendships",
  "Let's make talking fun again",
  "Time to turn small talk into real talk",
  "Everyone wants to connect. You're not alone",
  "The best stories start with a simple hi",
  "People are waiting to meet someone like you",
  "Let's break the ice together",
  "Talk more, worry less",
  "Every friend was once a stranger",
  "One chat can change your whole day",
  "Let's make talking to new people feel normal",
  "The best chats start right here",
  "People want to hear what you have to say",
  "Someone out there needs to hear from you",
  "Let's bring back real talks",
  "Skip the small talk, make real friends",
  "Everyone's looking to connect",
  "One hello can open so many doors",
  "Let's make talking to people less scary",
  "Good things happen when people talk",
  "You're one conversation away from a new friend",
  "Let's get people talking again",
  "Real friends start with real talks",
  "Time to meet your new favorite people",
  "Let's make talking feel natural again",
  "Everyone's hoping to meet someone new",
  "The best chats happen when you're just you",
  "One chat can change everything",
  "Let's get back to real talks",
  "People are nicer than you think",
  "Good talks lead to great things",
  "Let's make new friends today",
  "Everyone wants someone to talk to",
  "Real talks beat small talk any day",
  "Let's turn strangers into friends",
  "The best moments start with hello",
  "People are waiting to meet you",
  "One talk can brighten someone's day",
  "Let's make connections that matter",
  "Everyone's looking for someone to talk to",
  "Good people are just one hello away",
  "Let's make talking feel good again",
  "Real connections start with you",
  "Time to meet your kind of people",
  "Let's make every chat count",
]

export const getInitialMessage = () => {
  const randomIndex = Math.floor(Math.random() * loaderMessages.length)
  return loaderMessages[randomIndex]
}
